language: scala

scala:
- 2.11.4

jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false 

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
  - $HOME/.m2

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Not a PR Build" && [ "IS_${TRAVIS_TAG}" != "IS_" ] && echo "Is tag build $TRAVIS_TAG" || echo "."'
- '[ "IS_${TRAVIS_TAG}" != "IS_" ] && mvn versions:set -DnewVersion=$TRAVIS_TAG || true'

install:
- 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'

before_script:
- test "$TRAVIS_PULL_REQUEST" == "false" && git clone -b travis `git config --get remote.origin.url` target/travis || true

script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Deploying..." && mvn deploy --settings target/travis/settings.xml || echo "Testing..." && mvn test -B'

after_success:
- '[ "$TRAVIS_TAG" != "" ] && mvn site-deploy -P github-site -Dgithub.global.oauth2Token=$GITHUB_TOKEN || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_TAG" = "" ] && mvn scoverage:report || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn coveralls:report || true'


env:
  global:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
  - secure: ZlMzvn7Jlxbzbd8MNsxerPVPiTXXYdRj6i+AhyYN69nmjF9Re5Y6xaViEpxqL7jXL/0qQUKtM2he7TJFxzuhxZc32N0OCQ0euCuE6krBygRZ7Re+CFKEjGp1WCnySDpcpqWeDYKAvk6OtWm5q3TW+pFwF0UT/aL7xT0wdJrN8fU=
  - secure: oi5wtujkvD+B6oUEl8xFaW7bv2KilVX+v1mxS9WH5lHH0ei0RdCPbDcUR+9wqEfMzybPfmazvgK2UFk6GfrSuIR33iSJ3+MG9UMApUlX9eSgn7QM2OfZa/sLNjTKCjDnsTpRE+59VPBGEQsRTWVm2fl/iffyRZ/ervtd+qffcy8=
  - secure: UEwEEb3YXIgwofNBaaKBuqiyTNXOAqjfvJ+zPU6lUqJsoqPfemWL4Ikb7K8bA2domIgVAiMKmPm3FCAKFeeqm2QLRt0MQmqW6RUmKWFm2/12w9m3CFvTnBpDDdk8HUleXxs1FFZdflWYecBmoJqq8djO/wz7dJbPuPZkKU1NlLM=
  - secure: IP0Y5ARS9OfOP+RNFfBR7VwzQq9QSvFIAqsvXvyyxbKw8senacCyUa/rl2+naj7tIjuDyfUQGgMLuK8espx19ccZFN6UXNGS9izVjYbd7jKPviTZ4vCpqliz4FECux0tikWYV/AfwIf8hCKihdedl18/5kzU5tGz1JJQRP6T5ps=
  - secure: JnB8wDYEB7CzeNdAdTRrhX7TWS9yM/BNQxd4rF95pTXEhPyBAaYFMgHcauWfRurlbPPwDGIsuEvLQR+eYpp9xScJilgxKT6O1IIPVoZAbd6q+i2Qj4woh+++/M7opvbBlbyCBzlyVC9CZ0xDQo7rt+pxGjNnMYHG2SftcOkjlpU=
